// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sessionise_
List sessionise_(List split_timestamps, int threshold, int out_nrow);
RcppExport SEXP _reconstructr_sessionise_(SEXP split_timestampsSEXP, SEXP thresholdSEXP, SEXP out_nrowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type split_timestamps(split_timestampsSEXP);
    Rcpp::traits::input_parameter< int >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type out_nrow(out_nrowSEXP);
    rcpp_result_gen = Rcpp::wrap(sessionise_(split_timestamps, threshold, out_nrow));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_reconstructr_sessionise_", (DL_FUNC) &_reconstructr_sessionise_, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_reconstructr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
