# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sessionise_ <- function(split_timestamps, threshold, out_nrow) {
    .Call(`_reconstructr_sessionise_`, split_timestamps, threshold, out_nrow)
}

