# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sessionise_ <- function(split_timestamps, threshold, out_nrow) {
    .Call('reconstructr_sessionise_', PACKAGE = 'reconstructr', split_timestamps, threshold, out_nrow)
}

