# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title
#'sessionise
#'
#'@description
#'split a series of timestamps (or a series of series) associated with UUIDs, into sessions
#'
#'@details
#'\code{sessionise} splits timestamps associated with user events into "sessions",
#'enabling the simple calculation of various metrics such as session length or the number of events
#'within a session.
#'
#'@param timestamps a list of vectors of second values. These can be extracted by converting
#'POSIXlt or POSIXct timestamps into numeric elements through a call to \code{\link{as.numeric}},
#'or with the assistance of \code{\link{to_seconds}}.
#'
#'@param threshold the threshold, in seconds, for splitting out a new session. Set to 
#'3600 (one hour) by default.
#'
#'@return a list of vectors, each one representing a single session.
#'The returned list can be conveniently
#'passed into \code{\link{session_length}} or \code{\link{session_events}} for further analysis.
#'
#'@seealso \code{\link{session_length}} for calculating session length, \code{\link{bounce_rate}} for
#'calculating the bounce rate, and \code{\link{session_events}} for calculating the number of events in each session.
#'
#'@examples
#'#Take the inbuilt dataset and sessionise it
#'data("session_dataset")
#'session_dataset$timestamp <- to_seconds(x = session_dataset$timestamp, format = "%Y%m%d%H%M%S")
#'events_by_user <- split(session_dataset$timestamp, session_dataset$UUID)
#'sessions <- sessionise(events_by_user)
#'@export
sessionise <- function(timestamps, threshold = 3600L) {
    .Call('sessionreconstruct_sessionise', PACKAGE = 'sessionreconstruct', timestamps, threshold)
}

#'@export
session_length <- function(sessions, padding_value = 430L, preserve_single_events = FALSE, strip_last = FALSE) {
    .Call('sessionreconstruct_session_length', PACKAGE = 'sessionreconstruct', sessions, padding_value, preserve_single_events, strip_last)
}

#'@export
session_events <- function(sessions) {
    .Call('sessionreconstruct_session_events', PACKAGE = 'sessionreconstruct', sessions)
}

